### ISSUE TITLE
Handle gets triggered when scrolled

### ISSUE THREAD

**Issue by Skyost** [BendixMa/implicitly_animated_reorderable_list#3]
Hi,

I think I've found another bug. When you scroll the list while tapping on a `Handle` widget, it gets triggered and the list reorders itself. See :

![untitled](https://user-images.githubusercontent.com/3882599/76171782-67540a80-618f-11ea-98b2-790d83f59a9f.gif)

The scroll should have priority on reorder (well, I think it's the expected behavior).

**Comment by BendixMa** [comment]
Did you set the `delay` parameter on the `Handle`?

**Comment by Skyost** [comment]
Yes, I set a delay of [900 ms](https://github.com/Skyost/UnicaenTimetable/blob/dart-rewrite/lib/pages/home/cards/card.dart#L27).

**Comment by BendixMa** [comment]
Okay, well that's weird. The `Handle` should already make sure that it only initiates a reorder when the list didn't scroll. Alas, I'm quite busy this week so I won't be able to have a look at this until next week.

**Comment by Skyost** [comment]
No problem :wink:

**Comment by BendixMa** [comment]
Hey, 
I just released version `0.1.10` that should fix this issue. Could you check it out and see if it works now?

**Comment by Skyost** [comment]
Works perfectly, thank you !
