### ISSUE TITLE
Issues when using StreamBuilder

### ISSUE THREAD

**Issue by esDotDev** [BendixMa/implicitly_animated_reorderable_list#4]
This is a bit of a hail mary, but hopefully you can help push me in the right direction.

I have a todo list, that is tied to a document collection in firestore, which means a list wrapped in a StreamBuilder. 

For some reason, when using ImplicitlyAnimatedReorderableList my list items never rebuild when I push data to firestore. Switching to a standard ListView immediately fixed the issue. 

It's hard to isolate a good example for you, but here is a video where you can see the simple switch working: http://screens.gskinner.com/shawn/2020-03-10_00-38-06.mp4

**Comment by BendixMa** [comment]
From what I've seen from your code, everything seems fine and should be working. Could you maybe share the code on how you build you're items?

**Comment by esDotDev** [comment]
Ya it's very weird, the StreamBuilder just refuses to rebuild, even though the call is going through. I can see it get changed in Firestore, and if I close and re-open, the data is correct, but for some reason when using this list, the Stream just doesn't fire.

Here's my item code:
http://screens.gskinner.com/shawn/studio64_2020-03-10_09-03-44.png

Here you can see the calls going through to firestore in both cases, but with this list, it doesn't rebuild:
http://screens.gskinner.com/shawn/2020-03-10_09-07-06.mp4

**Comment by esDotDev** [comment]
I think I figured it out :) The issue seems to stem from using the "item" in the item builder. When I just look up the item using index, all works good.  

So in the code above, this was basically the fix. Change:
itemBuilder: (c, anim, item, i) => _buildReorderableItem(c, anim, **item**),

itemBuilder: (c, anim, item, i) => _buildReorderableItem(c, anim, **ordered[i]**),

**Comment by BendixMa** [comment]
Ok, but usually you shouldn't have to rely on the `index` parameter as the `item` represents the state of the list internally. Using the `index` could mean that the list gets out of sync with its underlying data. 

Alas, I'm very busy currently and probably won't have the time to look at this more thoroughly until next week. I'm gonna leave this open for now.

**Comment by esDotDev** [comment]
Ok, I did get it down to a very simple reproduction case:
```
//Get reference to firestore collection
listRef = getSingleton<FamilyFirestoreService>().getLists().document(widget.listId);
itemsRef = listRef.collection(FireParams.kItems);
```

```
return StreamBuilder<QuerySnapshot>(
        stream: state.itemsRef.snapshots(),
        builder: (context, AsyncSnapshot<QuerySnapshot> itemsSnapshot) {
          var ordered = itemsSnapshot.data.documents;
          return Container(
              color: Colors.white,
              child:
              ImplicitlyAnimatedReorderableList<DocumentSnapshot>(
                dragDuration: Duration(milliseconds: 350),
                items: ordered,
                areItemsTheSame: (item1, item2) => item1.documentID == item2.documentID,
                onReorderFinished: (item, from, to, newItems) => state.handleListReorder(newItems),
                itemBuilder: (c, anim, item, i) => Reorderable(
                  key: ValueKey(1),
                  builder: (_, __, ___) {
                    //item = ordered[i];
                    return GestureDetector(
                      onTapUp: (d)=>state.handleToggleCompleteTapped(item.documentID, !item.data[FireParams.kIsComplete]),
                      child: Container(color: ordered[i].data[FireParams.kIsComplete] ? Colors.red : Colors.blue, height: 50));
                  },
                ),
              ));
        });
```

```
void handleToggleCompleteTapped(String documentID, bool value) async {
    await itemsRef.document(documentID).setData(
      {FireParams.kIsComplete: value},
      merge: true,
    );
  }
```

**Comment by esDotDev** [comment]
Seeing some more weirdness, might help you track things down: In this case, I'm changing the parent collection, causing a full list rebuild. With normal list, it works great, with Reorderable, I'm getting duplicate items:
http://screens.gskinner.com/shawn/2020-03-10_12-55-50.mp4

I don't know where these extra items are coming from, printing out _ordered.length_ shows that it never exceeds 3 items.

**Comment by BendixMa** [comment]
Are you sure then that `areItemsTheSame` only returns `true` for exactly one item in the list? This is to say that `documentID` must be unique for every item in the list if you use it in the callback.

**Comment by esDotDev** [comment]
Ya, should be, the document id's are the id's of the documents in Firebase, which are guaranteed unique. Here you can see the 3 doc ids in the _path field (the characters after "/items/")
http://screens.gskinner.com/shawn/studio64_2020-03-10_14-01-37.png

**Comment by esDotDev** [comment]
In an effort to ease your testing, I've whittled it down to this example. You do still need a working firestore service
```
class ReorderableStreamSpike extends StatefulWidget {
  @override
  _ReorderableStreamSpikeState createState() => _ReorderableStreamSpikeState();
}

class _ReorderableStreamSpikeState extends State<ReorderableStreamSpike> {
  CollectionReference itemsRef;

  void initState() {
    //Grab some document in firestore
    DocumentReference listRef = Firestore.instance.collection('lists').document("somelist");
    itemsRef = listRef.collection("items");
    itemsRef.getDocuments().then((QuerySnapshot query) {
      if (query.documents.length < 3) for (var i = 3; i-- > 0;) itemsRef.add({"isComplete": false});
    });
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    //To reproduce:
    // Set to false, click the rows, and observe as "true/false" does not get updated.
    // Set to true, and observe as it does.
    bool useRegularList = false;
    return StreamBuilder<QuerySnapshot>(
      stream: itemsRef.snapshots(),
      builder: (c, snapshot) {
        if (!snapshot.hasData) return Container();
        List<DocumentSnapshot> docs = snapshot.data.documents;
        return (useRegularList)
            ? ListView.builder(
                itemCount: snapshot.data.documents.length,
                itemBuilder: (c, i) {
                  DocumentSnapshot item = snapshot.data.documents[i];
                  return _buildRow(item.documentID, item.data["isComplete"]);
                })
            : ImplicitlyAnimatedReorderableList(
                onReorderFinished: (item, from, to, newItems) {},
                areItemsTheSame: (DocumentSnapshot first, DocumentSnapshot second) => first.documentID == second.documentID,
                items: docs,
                itemBuilder: (c, anim, DocumentSnapshot item, i) => Reorderable(
                  key: ValueKey(item),
                  builder: (c, anim, drag) {
                    return _buildRow(item.documentID, item.data["isComplete"]);
                  },
                ),
              );
      },
    );
  }

  Widget _buildRow(String id, bool isComplete) {
    return RaisedButton(
        onPressed: () => itemsRef.document(id).setData({FireParams.kIsComplete: !isComplete}, merge: true),
        child: Row(
          children: <Widget>[
            Text("$id: $isComplete", style: TextStyle(color: Colors.white)),
          ],
        ));
  }
}
```

**Comment by BendixMa** [comment]
Thanks for your efforts! I've had a second look at your `itemBuilder` code of the initial example and saw that you're not using the animation of the `itemBuilder`. The list is based on `AnimatedList` so it expects you to use some sort of transition like `FadeTransition`, `SizeTransition` etc. To fade between item insertions, deletions or moves. This might be the reason for the duplicate items.

**Comment by esDotDev** [comment]
Thanks for the idea, but no luck :(
http://screens.gskinner.com/shawn/2020-03-11_01-13-43.mp4

**Comment by BendixMa** [comment]
But are you reordering the underlying data in firestore after the reorder has finished?

~~~dart
onReorderFinished: (item, from, to, newItems) {
                  setState(() {
                    //Set some data on the parent document, this will cause a rebuild of the stream, 
                    // and the duplicate rows issue will manifest
                    docRef.setData({"foo": Random().nextInt(999)});
                  });
                },
~~~

**Comment by esDotDev** [comment]
Not in that simple example, but I am in my actual application.

**Comment by esDotDev** [comment]
Ok, so I properly implemented the SizedFade transition as per your example, and now I'm getting perfect re-ordering. Sorry for the noise on that one. 

The issue with the list items not rebuilding when the firestore document is updated is still an issue however.

**Comment by BendixMa** [comment]
I think I was able to reproduce what you mean, although I'm not a Firebase pro. Could you check out version `0.1.10` and see if it works now?

**Comment by talatkuyuk** [comment]
> Ok, so I properly implemented the SizedFade transition as per your example, and now I'm getting perfect re-ordering. Sorry for the noise on that one.
> The issue with the list items not rebuilding when the firestore document is updated is still an issue however.

According to my experience in firebase, you should check whether you have created an index on firestore collection. The reason of stream doesn't update may be caused since there is no index on firestore.

**Comment by esDotDev** [comment]
Thanks I will check soon! Sorry for the lack of responses, just been busy.
